/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v8.0
processor: MKL46Z256xxx4
package_id: MKL46Z256VLL4
mcu_data: ksdk2_0
processor_version: 8.0.1
board: FRDM-KL46Z
pin_labels:
- {pin_num: '87', pin_signal: LCD_P31/PTC11/I2C1_SDA/I2S0_RXD0/LCD_P31_Fault, label: 'J1[15]/I2S_RXD', identifier: DB7}
- {pin_num: '86', pin_signal: LCD_P30/PTC10/I2C1_SCL/I2S0_RX_FS/LCD_P30_Fault, label: 'J1[13]/I2S_RX_FS', identifier: DB6}
- {pin_num: '83', pin_signal: LCD_P27/CMP0_IN1/PTC7/SPI0_MISO/USB_SOF_OUT/I2S0_RX_FS/SPI0_MOSI/LCD_P27_Fault, label: 'J1[11]/SOF_OUT', identifier: DB5}
- {pin_num: '82', pin_signal: LCD_P26/CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/I2S0_RX_BCLK/SPI0_MISO/I2S0_MCLK/LCD_P26_Fault, label: 'J1[9]/I2S_RX_BCLK', identifier: DB4}
- {pin_num: '80', pin_signal: LCD_P24/PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/TPM0_CH3/I2S0_MCLK/LCD_P24_Fault, label: 'J1[7]/I2S_MCLK', identifier: RS}
- {pin_num: '72', pin_signal: LCD_P22/ADC0_SE11/TSI0_CH15/PTC2/I2C1_SDA/TPM0_CH1/I2S0_TX_FS/LCD_P22_Fault, label: 'J4[10]/A4', identifier: RW}
- {pin_num: '71', pin_signal: LCD_P21/ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0/I2S0_TXD0/LCD_P21_Fault, label: 'J4[12]/A5', identifier: E}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '1', peripheral: UART1, signal: TX, pin_signal: LCD_P48/PTE0/SPI1_MISO/UART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA/LCD_P48_Fault}
  - {pin_num: '2', peripheral: UART1, signal: RX, pin_signal: LCD_P49/PTE1/SPI1_MOSI/UART1_RX/SPI1_MISO/I2C1_SCL/LCD_P49_Fault}
  - {pin_num: '87', peripheral: GPIOC, signal: 'GPIO, 11', pin_signal: LCD_P31/PTC11/I2C1_SDA/I2S0_RXD0/LCD_P31_Fault, direction: OUTPUT}
  - {pin_num: '86', peripheral: GPIOC, signal: 'GPIO, 10', pin_signal: LCD_P30/PTC10/I2C1_SCL/I2S0_RX_FS/LCD_P30_Fault, direction: OUTPUT}
  - {pin_num: '83', peripheral: GPIOC, signal: 'GPIO, 7', pin_signal: LCD_P27/CMP0_IN1/PTC7/SPI0_MISO/USB_SOF_OUT/I2S0_RX_FS/SPI0_MOSI/LCD_P27_Fault, direction: OUTPUT}
  - {pin_num: '82', peripheral: GPIOC, signal: 'GPIO, 6', pin_signal: LCD_P26/CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/I2S0_RX_BCLK/SPI0_MISO/I2S0_MCLK/LCD_P26_Fault,
    direction: OUTPUT}
  - {pin_num: '80', peripheral: GPIOC, signal: 'GPIO, 4', pin_signal: LCD_P24/PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/TPM0_CH3/I2S0_MCLK/LCD_P24_Fault, direction: OUTPUT}
  - {pin_num: '72', peripheral: GPIOC, signal: 'GPIO, 2', pin_signal: LCD_P22/ADC0_SE11/TSI0_CH15/PTC2/I2C1_SDA/TPM0_CH1/I2S0_TX_FS/LCD_P22_Fault, direction: OUTPUT}
  - {pin_num: '71', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: LCD_P21/ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0/I2S0_TXD0/LCD_P21_Fault,
    direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t E_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC1 (pin 71)  */
    GPIO_PinInit(BOARD_INITPINS_E_GPIO, BOARD_INITPINS_E_PIN, &E_config);

    gpio_pin_config_t RW_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC2 (pin 72)  */
    GPIO_PinInit(BOARD_INITPINS_RW_GPIO, BOARD_INITPINS_RW_PIN, &RW_config);

    gpio_pin_config_t RS_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC4 (pin 80)  */
    GPIO_PinInit(BOARD_INITPINS_RS_GPIO, BOARD_INITPINS_RS_PIN, &RS_config);

    gpio_pin_config_t DB4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC6 (pin 82)  */
    GPIO_PinInit(BOARD_INITPINS_DB4_GPIO, BOARD_INITPINS_DB4_PIN, &DB4_config);

    gpio_pin_config_t DB5_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC7 (pin 83)  */
    GPIO_PinInit(BOARD_INITPINS_DB5_GPIO, BOARD_INITPINS_DB5_PIN, &DB5_config);

    gpio_pin_config_t DB6_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC10 (pin 86)  */
    GPIO_PinInit(BOARD_INITPINS_DB6_GPIO, BOARD_INITPINS_DB6_PIN, &DB6_config);

    gpio_pin_config_t DB7_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC11 (pin 87)  */
    GPIO_PinInit(BOARD_INITPINS_DB7_GPIO, BOARD_INITPINS_DB7_PIN, &DB7_config);

    /* PORTC1 (pin 71) is configured as PTC1 */
    PORT_SetPinMux(BOARD_INITPINS_E_PORT, BOARD_INITPINS_E_PIN, kPORT_MuxAsGpio);

    /* PORTC10 (pin 86) is configured as PTC10 */
    PORT_SetPinMux(BOARD_INITPINS_DB6_PORT, BOARD_INITPINS_DB6_PIN, kPORT_MuxAsGpio);

    /* PORTC11 (pin 87) is configured as PTC11 */
    PORT_SetPinMux(BOARD_INITPINS_DB7_PORT, BOARD_INITPINS_DB7_PIN, kPORT_MuxAsGpio);

    /* PORTC2 (pin 72) is configured as PTC2 */
    PORT_SetPinMux(BOARD_INITPINS_RW_PORT, BOARD_INITPINS_RW_PIN, kPORT_MuxAsGpio);

    /* PORTC4 (pin 80) is configured as PTC4 */
    PORT_SetPinMux(BOARD_INITPINS_RS_PORT, BOARD_INITPINS_RS_PIN, kPORT_MuxAsGpio);

    /* PORTC6 (pin 82) is configured as PTC6 */
    PORT_SetPinMux(BOARD_INITPINS_DB4_PORT, BOARD_INITPINS_DB4_PIN, kPORT_MuxAsGpio);

    /* PORTC7 (pin 83) is configured as PTC7 */
    PORT_SetPinMux(BOARD_INITPINS_DB5_PORT, BOARD_INITPINS_DB5_PIN, kPORT_MuxAsGpio);

    /* PORTE0 (pin 1) is configured as UART1_TX */
    PORT_SetPinMux(PORTE, 0U, kPORT_MuxAlt3);

    /* PORTE1 (pin 2) is configured as UART1_RX */
    PORT_SetPinMux(PORTE, 1U, kPORT_MuxAlt3);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART1TXSRC_MASK | SIM_SOPT5_UART1RXSRC_MASK)))

                  /* UART1 Transmit Data Source Select: UART1_TX pin. */
                  | SIM_SOPT5_UART1TXSRC(SOPT5_UART1TXSRC_UART_TX)

                  /* UART1 Receive Data Source Select: UART1_RX pin. */
                  | SIM_SOPT5_UART1RXSRC(SOPT5_UART1RXSRC_UART_RX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
