/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART1RXSRC_UART_RX 0x00u /*!<@brief UART1 Receive Data Source Select: UART1_RX pin */
#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART1 Transmit Data Source Select: UART1_TX pin */

/*! @name PORTC11 (number 87), J1[15]/I2S_RXD
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DB7_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_DB7_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DB7_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DB7_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DB7_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DB7_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTC10 (number 86), J1[13]/I2S_RX_FS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DB6_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_DB6_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DB6_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DB6_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DB6_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DB6_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTC7 (number 83), J1[11]/SOF_OUT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DB5_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_DB5_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DB5_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DB5_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DB5_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DB5_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC6 (number 82), J1[9]/I2S_RX_BCLK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DB4_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_DB4_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DB4_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DB4_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DB4_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DB4_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC4 (number 80), J1[7]/I2S_MCLK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RS_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RS_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RS_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RS_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RS_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RS_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTC2 (number 72), J4[10]/A4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RW_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_RW_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RW_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RW_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RW_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RW_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTC1 (number 71), J4[12]/A5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_E_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_E_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_E_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_E_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_E_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_E_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
